version: 2
updates:
  - package-ecosystem: "pub"
    directory: "/router"
    schedule:
      interval: "weekly"
    groups:
      router-deps:
        patterns:
          - "*"

  - package-ecosystem: "npm"
    directory: "/bridge"
    schedule:
      interval: "weekly"
    groups:
      bridge-deps:
        patterns:
          - "*"

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
