name: router
description: A server app using the shelf package and Docker.
version: 1.9.31
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.10.4

dependencies:
  shelf: ^1.4.2
  shelf_router: ^1.1.2
  shelf_cors_headers: ^0.1.0
  dart_ipfs: ^1.7.3
  uuid: ^4.5.2
  crypto: ^3.0.7
  sqlite3: ^3.1.1
  path: ^1.8.3

  http: ^1.6.0
  mailer: ^6.0.0
  googleapis_auth: ^2.0.0
  dart_jsonwebtoken: ^3.3.1
  pointycastle: 4.0.0
  shelf_static: ^1.1.3
  dotenv: ^4.2.0

dev_dependencies:
  build_runner: ^2.10.4
  fake_async: ^1.3.3
  lints: ^6.0.0
  mockito: ^5.6.1
  test: ^1.25.6
