name = "seedsphere-bridge"
main = "src/index.ts"
compatibility_date = "2024-01-01"

[vars]
ROUTER_URL = "https://seedsphere.fly.dev"

[[kv_namespaces]]
binding = "KV_CACHE"
id = "57ad11f948c445b5a198bd4f888c64f6"
preview_id = "seedsphere_cache_kv_preview"

# Standard Stremio Addon Routes
# /manifest.json
# /stream/:type/:id.json
# /configure (Optional UI)
